apiVersion: v1
kind: Service
metadata:
  name: flink-nodeports
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30000
    port: 8081
  selector:
    app: basic-example
    component: jobmanager
    type: flink-native-kubernetes
